### ISSUE TITLE
Flash overflowed 

### ISSUE THREAD

**Issue by tuxcnc** [scottalford75/Remora-RT1052-cpp#1]
/usr/local/mcuxpressoide-11.7.1_9221/ide/plugins/com.nxp.mcuxpresso.tools.linux_11.7.1.202301190959/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: remora-rt1052-cpp.axf section `.text' will not fit in region `BOARD_FLASH'
/usr/local/mcuxpressoide-11.7.1_9221/ide/plugins/com.nxp.mcuxpresso.tools.linux_11.7.1.202301190959/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: region `BOARD_FLASH' overflowed by 59184 bytes
Memory region         Used Size  Region Size  %age Used
     BOARD_FLASH:      321328 B       256 KB    122.58%
        SRAM_DTC:       98816 B       128 KB     75.39%
        SRAM_ITC:        2040 B       128 KB      1.56%
         SRAM_OC:       43440 B       256 KB     16.57%
collect2: error: ld returned 1 exit status
make[1]: *** [makefile:90: remora-rt1052-cpp.axf] Błąd 1
make: *** [makefile:81: all] Błąd 2
"make -r -j12 all" terminated with exit code 2. Build might be incomplete.

**Comment by scottalford75** [comment]
I thought I fixed that in the last push..

There was a type in the MCU settings / Memory Details. Add an extra 0 to the BOARD_FLASH to be 0x400000. ie 4MB
