### ISSUE TITLE
Directional change small movement

### ISSUE THREAD

**Issue by Geramy** [scottalford75/Remora-RT1052-cpp#13]
It seems on a directional change my indicator moves only about 1/4 the value of what it should.
EXAMPLE:
If I move 0.254mm left and right it will miss 0.00254mm but if i keep advancing and not change the direction it will move the appropriate 0.254mm Not sure in where this problem lies?

**Comment by Geramy** [comment]
Kind of bad quality but I hope you can see what I’m talking about. I’m still trying to understand how the DMA math works exactly, I get most of it. But the accumulator and remainder part I’m not too sure about. It seems that each int32 can set 32 pins all at the same time inside the buffer for each int32. But I still don’t get how the speed portion works. Probably if I debugged the crap out of it I would understand more. But anyways the only thing I can think of is we need more space inside a dir change before a pulse and I’m not sure how to add that. It would seem I could add a offset in here but I’m not sure how that would change the rest of the code.
https://github.com/scottalford75/Remora-RT1052-cpp/assets/264964/eae19549-01a9-4848-babc-4ce9a9e0a08e

**Comment by scottalford75** [comment]
I'm so happy your able to do real physical testing, 

A direction change can only happen at the beginning of the new DMA buffer, when we see a change in the sign of the frequency command. I currently flip the direction bit right at the start of the buffer.

https://github.com/scottalford75/Remora-RT1052-cpp/blob/a1c1569f6d239b6d6719d51c4717de0bb8578ccf/Remora-RT1052-cpp/source/modules/DMAstepgen/DMAstepgen.cpp#L166

My thought was that at a direction change, the velocity would be so low that it would be unlikely to have a step within the same servo period, and this is what I have observed on the logic analyser output. But, it would be possible to ensure the required direction hold time by changing the code. I'll need to think of the best place to put it.

BTW, what is your step scale. is the 0.00254mm miss equal to a step?

**Comment by Geramy** [comment]
My dead and or lowest step is 1 / 2000 or 0.0005mm I might change my step resolution to something lower but I’m not sure that’s gonna fix any miss steps I’m seeing. We seem to have a miss step somewhere. My steppers are in pure closed loop at the driver level.

**Comment by Geramy** [comment]
If I move 2.54mm in one direction which is 0.1” and then do it again in the same direction. I end up missing 0.001” or 0.0254mm I’m at 140,000hz everything else is the same. My drivers are 200,000hz maximum

**Comment by Geramy** [comment]
It’s kind of weird though because it’s not all the time either. It seems to be more or less also sometimes. most the time it’s way less. Thoughts? I been tearing the DMA code down trying to understand it haha. Maybe you could explain the theory behind your math?

**Comment by Geramy** [comment]
> I'm so happy your able to do real physical testing,
> 
> A direction change can only happen at the beginning of the new DMA buffer, when we see a change in the sign of the frequency command. I currently flip the direction bit right at the start of the buffer.
> 
> https://github.com/scottalford75/Remora-RT1052-cpp/blob/a1c1569f6d239b6d6719d51c4717de0bb8578ccf/Remora-RT1052-cpp/source/modules/DMAstepgen/DMAstepgen.cpp#L166
> 
> My thought was that at a direction change, the velocity would be so low that it would be unlikely to have a step within the same servo period, and this is what I have observed on the logic analyser output. But, it would be possible to ensure the required direction hold time by changing the code. I'll need to think of the best place to put it.
> 
> BTW, what is your step scale. is the 0.00254mm miss equal to a step?

I also thought this as well. I been reading the code racking my head on it and it seems to skip memory positions based on the step frequency right. So technically it would be really difficult if you had your hz setup right to run into a directional change. I thought it was backlash at first but I tested backlash before on mach3 with my e-cut motion card and I didn’t have any so it’s leaving me to think there is some sort of missing step at the beginning of the buffer or it has something to do with directional change.

**Comment by Geramy** [comment]
By the way if I’m missing 0.0254mm on a 2.54mm move that means we are missing 50.8 steps. What’s weird though if i zoom all the way across my table at about 1600mm/m or 1800 I end up only missing about 1 to 3mm not sure if that scales correctly?

**Comment by Geramy** [comment]
Just calculated it my table length on the X axis is about 287mm thats 2.8mm if i scale it. So for every 1mm we miss about 0.01mm, it just doesn’t make much sense to me. I dont understand how we could miss that much, the dmastepgen seems pretty simple, i did read that possible DMA is not the best for motor control and FlexIO is better, but cant find anything about FlexIO other than rt1052 has it haha.

**Comment by Geramy** [comment]
So if I advance the accumulator by the amount of dir setup time required then we have forward setup time, now as far as doing that for the stepLow case, not sure how im supposed to advance the accumulator for that, ideas? I submitted a commit for it on my main.

**Comment by Geramy** [comment]
https://github.com/AlecGMcNamara/Browser-oscilloscope/tree/master I should be able to say how many mm to move and calculate my deadband as the amount of rises or falls i have, in order to see if we are missing a step.

**Comment by scottalford75** [comment]
So, back in the workshop office today after a busy long weekend. I've just reviewed a step and direction trace I took last week and I can confirm that there are occasions when there is zero gap between a direction change and a step pulse. I'm scratching my head on the best implementation of a direction setup.

**Comment by Geramy** [comment]
Have you seen any errors in the actual steps? I am having the hardest time finding a library so i can use the ESP8266, it turns out maybe i can do GPIO and read the input signals to count it, but thats as far as i've gone. https://simpledevicemodel.github.io/

**Comment by Geramy** [comment]
I’m using your old DMA Stephen before you made the improvements that one is more or less stable. I’m still seeing missed steps not sure why. Or maybe I’m not it’s really hard to tell. The improvements you made on the speed caused 2.54mm movement to only be half of the movement not sure why. So back to the version without step length and step hold I am seeing still maybe 0.0254mm missing out of every 2.54mm move I don’t have the tools to scope it out properly at 100khz, ideas? Arduino, esp8622?

**Comment by Geramy** [comment]
I’m wondering if line 147 here https://github.com/scottalford75/Remora-RT1052-cpp/blob/feature/DMAstepgen/Remora-RT1052-cpp/source/modules/DMAstepgen/DMAstepgen.cpp
Can cause us to possibly loose steps? I see that its putting the low in the buffer probably somewhere at the start, but if it runs into the new buffer where the new step will be then it could literally run it over right and not make a step?

**Comment by scottalford75** [comment]
The earlier work had some real issues, inverted steps etc. Hence the work to improve / correct the bugs. Logic analyzer capture is much improved. I've just implemented the direction setup feature.

Frequencies look correct, but that said hard to tell without a physical axis.

![Screenshot 2023-10-04 121915](https://github.com/scottalford75/Remora-RT1052-cpp/assets/25348769/d5db63c8-da50-4f84-aff1-73779f6c5109)

I've pushed it to the repo

**Comment by scottalford75** [comment]
I just noticed this post

https://www.forum.linuxcnc.org/18-computer/44828-remora-ethernet-nvem-cnc-board?start=1160#281895

Are you running your steppers in velocity mode with encoder feedback to LinuxCNC? Remora does not have FF2 or I settings?

**Comment by Geramy** [comment]
I got the drivers in step dir and LinuxCNC in velocity I didn’t have pgain mapped in my Hal to remora haha. So I been changing values like a mad man and nothing was happening. Got my f-error under control, I don’t run encoders never needed too, never experienced skipped steps due to forces being too much. Tomorrow I’m gonna check to see if mach3 has any issues. But the framework of the systems are different. Mach 3 motion cards do all the planning and real time control on the card whereas LinuxCNC does the real-time operation. Is there some sort of latency or precision or something like that which could be throwing me off at 0.02mm per 1mm, perhaps pgain is too high, at 100 is what mine is set for as I tuned it watching f-error and using halcmd adjusting the pgain as I stepped.

**Comment by scottalford75** [comment]
Remora-nv default is position mode, ie using step count feedback. In the code, when we put a step into the DMA buffer, it then increments or decrements the step count feedback. So, lost steps is either by not respecting the step and direction timing (which I hope we've fixed) or physically losing steps.

Latency will only impact following error. I've got my Pgain dialed back down to 10. Higher numbers were causing following error spikes and oscillation.

**Comment by Geramy** [comment]
I did notice changing the frequency of the DMA does actually do weird things. There are some perfect frequency’s which is like 120,000hz when I do about 80,000hz I get that weird direction flip business so maybe also the missing step thing could be due to frequency and buffer size? Just throwing out ideas. I’ll give your firmware a test first thing in the morning and run it on my indicator. I double checked my indicator with a well known accurate Ballscrew jig I made earlier and the indicator I’m using is 100% accurate. I been thinking I’ve been going crazy because of this weird missing step phantom that’s been going on haha so I’m double checking nearly everything, wiring, grounds, checking to see if my CNC Case has voltage haha…. Who knows….. havnt found anything abnormal. Even set steppers to 1000 steps per mm instead of 2000. Same weird inaccuracy and it’s not always the same. Update you tomorrow with the changes you made.

**Comment by scottalford75** [comment]
I've got an 24v encoder coming, so I'll also set this up to check physical position of a stepper motor to test repeatability etc. I think we're getting close but I want to make sure this new code is as bullet proof as possible.

**Comment by Geramy** [comment]
> The earlier work had some real issues, inverted steps etc. Hence the work to improve / correct the bugs. Logic analyzer capture is much improved. I've just implemented the direction setup feature.
> 
> Frequencies look correct, but that said hard to tell without a physical axis.
> 
> ![Screenshot 2023-10-04 121915](https://user-images.githubusercontent.com/25348769/272436825-d5db63c8-da50-4f84-aff1-73779f6c5109.png)
> 
> I've pushed it to the repo

what oscilloscope do you have?

**Comment by Geramy** [comment]
Hey so i turned up the Step Space and Step Length to 6 and 6 and Dir Setup to 18. If I move in one direction or the other using Step mode not Continuous it doesnt stop moving ever...... it literally keeps moving, haha..... apparently this is our bug i think thats causing some sort of loss of steps. I'll attach a video your gonna love it.

**Comment by Geramy** [comment]
![photo_2023-10-04_10-48-21](https://github.com/scottalford75/Remora-RT1052-cpp/assets/264964/283e96a1-b412-4f09-9045-0a9432f271a4)

https://github.com/scottalford75/Remora-RT1052-cpp/assets/264964/79073e09-6128-4098-bb9e-96e0e3bf5ed3

**Comment by Geramy** [comment]
Seems to be after a json upload to the board without powering it down fully and back up.
Looks like with the step variables and direction im not getting any problems with changing direction and stepping.

**Comment by Geramy** [comment]
So I am noticing Pulse - has voltage and Pulse + doesnt, testing voltage against case ground, I am going to wire all negatives of the steppers to com negative. I'm not sure why its like that Pulse -, and Dir - should be sunk to ground permanently.

**Comment by Geramy** [comment]
XP-, XDIR- and all the minus should be sunk to ground, on my board I can see those two flip between positive and negative based on who knows what. I routed X P- and D- to Com - and now im not missing steps and we will see about direction. Do you have those pinouts for those, so I can program them as Input so they are constantly sunk to ground?

**Comment by Geramy** [comment]
The pinouts you have for ZP+ is not + its the - Pin.

**Comment by Geramy** [comment]
So to confirm, I sunk all Drivers - to Com ground and am using the + on the board for each respective axis and things seem to be working, milling stainless steel right now without a problem, no direction flips either and that small movement based on directional change is also gone. I believe the missing steps problem may also be gone, I will test it once I finish a job. I got to get some stainless steel stuff out the door.

**Comment by Geramy** [comment]
![IMG_9149](https://github.com/scottalford75/Remora-RT1052-cpp/assets/264964/7013b9cb-f988-45a7-afeb-1612aaedacba)

i would probably say if there was any skipped steps or missing I’m not sure where they went haha. Some of these points are less than 1mm in depth so I mean skipped or missing steps add up I don’t see that at this point.

**Comment by scottalford75** [comment]
Great to hear that you've tracked down some issues, and also good to know the new stepgen is producing good results. Nice work. I wish I had a machine that could do that kind of work.

**Comment by Geramy** [comment]
Trust me it took a lot of work to make my machine good enough to do this, replaced most of the aluminum structure with structural steel bars 1" to 1.5" thick had them machined down locally, installed 12mm rails not the 15 :( or 20 :( and bought a spindle motor on amazon haha and of course had to design new mounts and stuff and order them from china or Xometry, but it worked out. If you need custom parts let me know, or design to fix up your machine.

**Comment by Geramy** [comment]
Tomorrow i'll upload my config with all the bells and whistles. I got Z tool height setter, and 3D touch probe, with manual tool change setup and working great, also with fusion 360 WCS/Probing with qtdragon for the GUI.

**Comment by Geramy** [comment]
Hey I still do sometimes get directional switches but its a rare case, and hasn't happened in the middle of milling, but happens with the jog wheel, i'm wondering, did you also add DirSetup for the following case?

```
// finish the step from the previous period if needed
if (this->isStepping)
{
// put step low into DMA buffer
*(stepDMAbuffer + this->stepLow) |= this->stepMask;
this->stepLow = 0;
this->isStepping = false;
}

// what's the direction for this period
if (this->frequencyCommand < 0)
{
this->dir = false; // backwards
}
else
{
this->dir = true; // forwards
}

// change of direction?
if (this->dir != this->oldDir)
{
// toggle the direction pin
*stepDMAbuffer |= this->dirMask;
this->oldDir = this->dir;
this->dirChange = true;
}
```

If i'm not mistaking a step low could happen at the same time as a dir change, that also has to have a setup time too.

For reference, correct me if i'm wrong.

![image](https://github.com/scottalford75/Remora-RT1052-cpp/assets/264964/ca6d6b82-6c4f-402e-8edb-8b4be5520a19)

**Comment by scottalford75** [comment]
Might be best to implement the dirHold, so that the direction change happens after the completion of the step like in the LinuxCNC timing diagram?

https://github.com/scottalford75/Remora-RT1052-cpp/blob/60a43e55928313290d27efb17a59eff4e9cb4553/Remora-RT1052-cpp/source/modules/DMAstepgen/DMAstepgen.cpp#L107

**Comment by scottalford75** [comment]
https://github.com/scottalford75/Remora-RT1052-cpp/blob/60a43e55928313290d27efb17a59eff4e9cb4553/Remora-RT1052-cpp/source/modules/DMAstepgen/DMAstepgen.cpp#L107-L120

**Comment by Geramy** [comment]
> Might be best to implement the dirHold, so that the direction change happens after the completion of the step like in the LinuxCNC timing diagram?
> 
> https://github.com/scottalford75/Remora-RT1052-cpp/blob/60a43e55928313290d27efb17a59eff4e9cb4553/Remora-RT1052-cpp/source/modules/DMAstepgen/DMAstepgen.cpp#L107

YeH that’s what I think too right

**Comment by Geramy** [comment]
Just submitted the change for that, please verify the pull request, after all the commits I want to make sure it doesnt effect your changes you made, I reverted and then pulled from you and then made my change but idk just verify please. Thanks for the hard work and see if you can attach the scope to verify my changes :), https://github.com/scottalford75/Remora-RT1052-cpp/pull/14

**Comment by Geramy** [comment]
Switched drivers I have no problems with steps anymore but my direction is never the same… I can open Linuxcnc make scale - or + close it open it again and something could be going in the wrong direction.

**Comment by Geramy** [comment]
Do you think it could be the wireless hand wheel?

**Comment by Geramy** [comment]
Turned on LinuxCNC X went backwards turned off switched scale to negative while y and z are positive. Turned on and now y and z move the other way. Does it have something to do with one axis is a negative scale while the others are all positive scale?

**Comment by Geramy** [comment]
Resided motors so they are all positive naturally and it seems to be working

**Comment by scottalford75** [comment]
The LinuxCNC side of things should be very robust after years of
development. Remember, the Remora controller is sending back what it has as
position count (actual step generated), so if LinuxCNC thinks things are
going the right direction / position it's because that is what the board is
doing / done. When used as a true differential pair, your step and
direction outputs should be relatively noise immune. Noise on each wire at
the same time is ignored as it's the voltage difference between the two
which is important. When grounding one side of the pair we lose that
advantage.

How do you feel about the DMA stephen? When I'm back I'll need to pull your
latest changes. I should also have an encoder by then so can do some of my
own physical checks.

**Comment by Geramy** [comment]
Sweet, I’ll keep that in mind and in Monday I’ll run tests on that, I’m wondering if the state of the board forgets it’s last direction or maybe from high pgain the oscillation is causing some weird flip that shouldn’t be there. I did notice when moving Y to certain positions I get oscillation and other times not. The DMA Step Gen seems pretty stable. I was having some issues in my other driver but I’m not sure that’s exactly the motion cards fault. I took apart my driver board which has a stm32 inside and thinking about finding a newer firmware for the same driver hardware version. Anyways steps seem awesomely stable. I surfaced a new bed for my CNC and did the fixture threaded holes. Row 2” and column 1.25” which my grid seems very accurate just that direction thing scares the heck out of me.
Been planning on this upgrade for almost a year now haha, your motion controller firmware made it possible and I feel it’s a lot more smooth

![camphoto_1297389768](https://github.com/scottalford75/Remora-RT1052-cpp/assets/264964/33cc19ce-1b6b-4581-be06-a159825f816b)
![IMG_9182](https://github.com/scottalford75/Remora-RT1052-cpp/assets/264964/d736540b-e113-49cb-aabd-4123ceaf2139)

**Comment by scottalford75** [comment]
Cool. Keep a eye on the direction issue thing and maybe there is a fringe
case that has not been addressed. On an e-stop I force the direction output
to a known state so that when we use the DR_TOGGLE register in the
DMAstepgen it's also in a known state. Maybe there are some cases where
it's not getting reset correctly.

**Comment by Geramy** [comment]
Yeah it’s really weird I’m not sure how it’s happening, maybe it has something to do with really really tiny movements like when we talked about pgain being too high causing oscillation and the motor going back and forth. Perhaps that could cause it but I didn’t see it in that case it’s just when I turn on everything it randomly changes it. Also when I turn on LinuxCNC sometimes it will change the position in LinuxCNC from last position to some weird new position like instead of 0.00 it will be 0.60 or -0.6 and even if I shut it down and reset the last position again back to 0.000 it will do the same.

**Comment by Geramy** [comment]
Going to close this out and maybe ill open another one more relevant with less comments, thanks on all the hard work! The directional change that exists now only has a certain case and is no longer a open large case scenario like before, now its very limited and i can replicate it a certain way.
