### ISSUE TITLE
Uploading json via tftp

### ISSUE THREAD

**Issue by Geramy** [scottalford75/Remora-RT1052-cpp#2]
Hey you may know this but on the dma changes it seems you cannot upload a new json file, once you upload a new json file over tftp the board stops responding, could possibly be due to the DMA addition, not sure. I don't get any exceptions or anything thrown through the debugger. Debugging this thing is like pulling teeth.

**Comment by Geramy** [comment]
It looks like its being blocked by DMA

**Comment by scottalford75** [comment]
I'll look into it, I haven't tried an upload with the DMA running. It should not be to difficult to halt the DMA when a TFTP packet arrives.
