### ISSUE TITLE
Error running nvem

### ISSUE THREAD

**Issue by Nvems** [scottalford75/Remora-RT1052-cpp#25]
Hello,
Maybe someone can help me
I try fresh install linuxcnc 2.9.1

I use nvem v2 with rt1052 with  firmware rt1052 V3.1.0
I add components remora-eth-3.0.c and remora-nv.c, i use config remora-ec500-DMA

but i got error like this 

Debug file information:
Note: Using POSIX realtime
ERROR: PRU base frequency incorrect
remora-nv: rtapi_app_main: Operation not permitted (-1)
./remora-ec500.hal:9: waitpid failed /usr/bin/rtapi_app remora-nv
./remora-ec500.hal:9: /usr/bin/rtapi_app exited without becoming ready
./remora-ec500.hal:9: insmod for remora-nv failed, returned -1
5016
Stopping realtime threads
Unloading hal components
Note: Using POSIX realtime

Did i _miss_ some steps
Thanks

**Comment by scottalford75** [comment]
Hi, the latest firmware requires remora-eth-3.0 which is loaded in your hal
file with the following. You will need to change the line to remove
remora-nv.

loadrt remora-eth-3.0 PRU_base_freq=500000

**Comment by Nvems** [comment]
ok..i got it
it can run after change that line

but if i running there always stop at running file,like video

https://github.com/scottalford75/Remora-RT1052-cpp/assets/151521646/73b5a766-ec09-413f-8b98-f1fc680cde8e

**Comment by scottalford75** [comment]
So this will be a config issue. Can you please share your hal and ini file?

**Comment by Nvems** [comment]
from github i olny change this  loadrt remora-eth-3.0 PRU_base_freq=500000 and min_limit and max limit
[Uploading remora-ec500-DMA.zip…]()

**Comment by scottalford75** [comment]
Thanks for sharing your files. I have run this on my test bench. What step length and step space have you setup on the board. The reason I ask is that your scale and max velocity values will put the stepgen at maximum when step length and step space are equal to 1. 

I have successfully run your config with stepLength = 1 and stepSpace = 1. Anything higher following errors like you've found.

**Comment by scottalford75** [comment]
I'd also look at your Pgain as it's aggressive kicking the spike filter into action.

**Comment by Nvems** [comment]
can you share the correct config for my reference, please

**Comment by scottalford75** [comment]
Probably best to start with understanding your stepper driver requirements
and then set up a config accordingly. What drivers are you using?

**Comment by Nvems** [comment]
I using driver leadshine CL86C stepper 86CME85 closed loop
For pulses in one revolution 6400 with reducer 1:4, rack gear M1.25 with pinion 25 teeth

**Comment by scottalford75** [comment]
Nice setup

For those drivers the following stepgen config:

Step Length 1
Step Space 1
Dir Setup 2
Dir Hold 2

So you will be able to max out the 500khz step generator.

Is my math right.. I calculate your SCALE as 819.2 steps / mm

**Comment by Nvems** [comment]
Okay with that the error is gone,, thanks you
How about pgain do i need to change the value


I create gcode with aspire 9.6 
If in gcode there M6 T1, my gcode cannot run,but if i remove it,,it can run normally 
Is normal with this config

**Comment by scottalford75** [comment]
Nothing to do with Remora, but the following should help.

https://forum.linuxcnc.org/38-general-linuxcnc-questions/44838-m6-and-manual-tool-change

**Comment by Nvems** [comment]
Ok i got it


with that config the nvem still gets "joint error" while running gcode,

**Comment by Nvems** [comment]
I get the problem, because i use 12v
I use 24v it can move freely
Thanks
