### ISSUE TITLE
Direction flips

### ISSUE THREAD

**Issue by Geramy** [scottalford75/Remora-RT1052-cpp#5]
Sometimes when moving with a wireless hand pendant the direction of a axis gets flipped, not sure why?
I noticed it even more in Release mode with speed optimizations and less in debug mode. Once it flips its permanently flipped reverse until you restart the card not linuxcnc.

**Comment by scottalford75** [comment]
Details? Type of hand pendant? Wired to normal IO with software encoder module?

**Comment by Geramy** [comment]
Wireless Hand controller connected directly to linuxcnc the hal file is xhc-whb04b-6.hal

**Comment by Geramy** [comment]
maybe its some sort of udp packet error, not sure how that would happen to be honest.

**Comment by Geramy** [comment]
Yeah still happening, not sure why, but it nearly caused a probe crash and death to my 3d probe, any idea where i should look to see why the bit is flipping or reversing, can it be a hal setting?

**Comment by Geramy** [comment]
So I adjusted the PID loop or well the P to 12 and the deadband to 0.001 and ferror to 0.1 and then adjusted the servo frequency to 67,000 which seemed to have fixed the problem, so far. but i'm wondering if this direction flip and me changing those settings is just a work around to fix a bug that exists? I need to calibrate the loop more which technically it shouldn't need because i'm using closed loop steppers on the board.

**Comment by scottalford75** [comment]
I can't see how this is an issue with Remora. Remora is just accepting a velocity (frequency) command from LinuxCNC. Something going on in the hal maybe...

**Comment by Geramy** [comment]
Okay, I'll see if I can track it down somehow, maybe its linuxcnc then, I do have the scale at a negative value, maybe i should put it positive and just flip my motors wirings on the driver side instead of using negative, I assume I'm not the only one who has a negative scale..

**Comment by Geramy** [comment]
Still seem to get this, i wrecked my probe earlier today, not sure whats causing these weird direction flips, it can’t be anything to do with the interrupts can it? It’s wrecking havoc in my system that and the f-error, I am doing roughly 1600mm per minute maximum thats about 18.75us per pulse to accomplish that, the drivers i use require 2.5us between high and low and i believe 5us for direction before a pulse can be sent. My linuxcnc jitter is about 60,000 typically and sometimes up to 120,000. I’m going to look at running linuxcnc on the pi 4 model b and see if that changes my f-error at all. Right now I’m using a dell wise 5060 quad core amd go-424cc, 4GB ram, Realtek r8168-dkms network card pci-e built-in, Debian bookworm with latest linuxcnc recommended and compiled rt kernel 6.11 i believe, whats the wait time for pulse and direction? Maybe thats whats causing the flipping on direction?

**Comment by Geramy** [comment]
Hey Scott it seems I am missing 5 steps also, Input step length to 4 maybe I should change the width instead?

**Comment by Geramy** [comment]
It seems that as I set the step length and step width I end up getting more and more inaccurate movements. if I set them back to 1 and make sure the frequency of DMA is at the pulse width i need like 200 or 300 it works correctly no missed steps. I believe whats going on is the counter perhaps is not taking into account something correct and reporting the wrong steps back to linuxcnc perhaps.

**Comment by Geramy** [comment]
I have Step Space set to 2 and Step Length set to 4 and I am  measuring if I move 2.54mm I miss 0.0762mm in the movement. or 0.003", i'm using measurement equipment to verify the movements so its 100% accurate.

**Comment by Geramy** [comment]
This seems to be a bug when compiling or frequency, i havn't isolated it yet, but im going to close it because it seems to be a compile issue.
